export interface Drill {
  id: string;
  name: string;
  sourcePage: string;
  sourceHref: string;
  defaultSets: number;
  defaultReps: number;
  workSeconds: number;
  restSeconds: number;
  instructions: string[];
}

export const DRILLS: Drill[] = [
  // Footwork Drills page
  {
    id: 'ball-drop-reaction',
    name: 'Ball Drop Reaction',
    sourcePage: 'Footwork Drills',
    sourceHref: '/footwork-drills',
    defaultSets: 3,
    defaultReps: 10,
    workSeconds: 30,
    restSeconds: 30,
    instructions: [
      'Partner holds a ball at shoulder height and drops it without warning.',
      'Sprint forward to catch the ball before it bounces twice.',
      'Focus on explosive first step and low athletic stance.',
      'Reset to starting position after each rep.',
    ],
  },
  {
    id: 'mirror-drill',
    name: 'Mirror Drill',
    sourcePage: 'Footwork Drills',
    sourceHref: '/footwork-drills',
    defaultSets: 4,
    defaultReps: 1,
    workSeconds: 30,
    restSeconds: 15,
    instructions: [
      'Face a partner on opposite sides of the service line.',
      'One player leads with lateral movements; the other mirrors.',
      'Stay in an athletic stance with knees bent throughout.',
      'Switch leader and follower roles each set.',
    ],
  },
  {
    id: 'x-drill',
    name: 'X-Drill',
    sourcePage: 'Footwork Drills',
    sourceHref: '/footwork-drills',
    defaultSets: 3,
    defaultReps: 1,
    workSeconds: 45,
    restSeconds: 45,
    instructions: [
      'Set up four cones in an X pattern on one side of the court.',
      'Start at the center cone and sprint to each outer cone in sequence.',
      'Touch each cone and return to center before moving to the next.',
      'Maintain split-step posture on each touch and keep hips low.',
    ],
  },
  {
    id: 'fan-drill',
    name: 'Fan Drill',
    sourcePage: 'Footwork Drills',
    sourceHref: '/footwork-drills',
    defaultSets: 2,
    defaultReps: 1,
    workSeconds: 60,
    restSeconds: 60,
    instructions: [
      'Place five cones in a fan pattern from the center baseline.',
      'Sprint to each cone from left to right, touching and recovering.',
      'Use proper split-step and recovery steps between each cone.',
      'Emphasize full recovery to center between each sprint.',
    ],
  },
  {
    id: 'service-box-suicide',
    name: 'Service Box Suicide',
    sourcePage: 'Footwork Drills',
    sourceHref: '/footwork-drills',
    defaultSets: 3,
    defaultReps: 1,
    workSeconds: 45,
    restSeconds: 45,
    instructions: [
      'Start at the singles sideline in the service box area.',
      'Sprint to the center service line, touch, and return.',
      'Then sprint to the opposite sideline, touch, and return.',
      'Keep each suicide continuous without stopping at the start.',
    ],
  },
  {
    id: 'zigzag-cone-sprint',
    name: 'Zigzag Cone Sprint',
    sourcePage: 'Footwork Drills',
    sourceHref: '/footwork-drills',
    defaultSets: 3,
    defaultReps: 1,
    workSeconds: 30,
    restSeconds: 30,
    instructions: [
      'Place 6 cones in a zigzag line down the court.',
      'Sprint through cones weaving left and right.',
      'Stay on balls of feet and drive off the outside foot at each turn.',
      'Walk back to start for the rest period.',
    ],
  },
  // Groundstrokes page
  {
    id: 'cross-court-20',
    name: 'Cross-Court 20',
    sourcePage: 'Groundstrokes',
    sourceHref: '/groundstrokes',
    defaultSets: 3,
    defaultReps: 20,
    workSeconds: 120,
    restSeconds: 30,
    instructions: [
      'Both players rally cross-court only, targeting inside the service box extension.',
      'Count to 20 consecutive balls without an error.',
      'Focus on consistent topspin and depth on every shot.',
      'If the count breaks, start over from zero.',
    ],
  },
  {
    id: 'figure-8-drill',
    name: 'Figure-8 Drill',
    sourcePage: 'Groundstrokes',
    sourceHref: '/groundstrokes',
    defaultSets: 3,
    defaultReps: 20,
    workSeconds: 120,
    restSeconds: 30,
    instructions: [
      'Players alternate between deuce cross-court and ad cross-court shots.',
      'Each ball traces a figure-8 path across the net.',
      'Count 20 balls to complete one rep of the pattern.',
      'Emphasize footwork recovery to the center after each shot.',
    ],
  },
  {
    id: 'deep-zone-rally',
    name: 'Deep Zone Rally',
    sourcePage: 'Groundstrokes',
    sourceHref: '/groundstrokes',
    defaultSets: 3,
    defaultReps: 1,
    workSeconds: 120,
    restSeconds: 30,
    instructions: [
      'Rally cross-court with every ball landing behind the service line.',
      'Any ball landing in the service boxes is considered an error.',
      'Focus on topspin, heavy balls, and driving through the contact point.',
      'Use a cone or target marker to define the deep zone boundary.',
    ],
  },
  {
    id: 'speed-ladder-rally',
    name: 'Speed Ladder Rally',
    sourcePage: 'Groundstrokes',
    sourceHref: '/groundstrokes',
    defaultSets: 3,
    defaultReps: 1,
    workSeconds: 120,
    restSeconds: 30,
    instructions: [
      'Place a speed ladder behind the baseline on one side.',
      'After each groundstroke, run through the ladder and recover.',
      'Partner feeds continuously to keep the rally going.',
      'Focus on quick footwork in the ladder and immediate split-step on return.',
    ],
  },
  {
    id: 'first-strike-drill',
    name: 'First-Strike Drill',
    sourcePage: 'Groundstrokes',
    sourceHref: '/groundstrokes',
    defaultSets: 3,
    defaultReps: 10,
    workSeconds: 60,
    restSeconds: 30,
    instructions: [
      'Coach or partner feeds a short ball to either corner.',
      'Player moves forward and hits an aggressive approach shot.',
      'Target the open court with depth and pace.',
      'Follow the ball to the net and finish with a volley if possible.',
    ],
  },
  // Training page
  {
    id: 'shadow-serve',
    name: 'Shadow Serve',
    sourcePage: 'Training',
    sourceHref: '/training',
    defaultSets: 3,
    defaultReps: 10,
    workSeconds: 60,
    restSeconds: 15,
    instructions: [
      'Perform the complete service motion without hitting a ball.',
      'Focus on trophy position, hip rotation, and pronation.',
      'Use a mirror or video to check form and timing.',
      'Slow down each phase to ingrain correct muscle memory.',
    ],
  },
  {
    id: 'target-practice-serves',
    name: 'Target Practice Serves',
    sourcePage: 'Training',
    sourceHref: '/training',
    defaultSets: 3,
    defaultReps: 1,
    workSeconds: 120,
    restSeconds: 30,
    instructions: [
      'Place targets (cones or towels) in the T, body, and wide zones.',
      'Serve to each target in rotation, calling the zone before each serve.',
      'Track hit percentage for each zone over the session.',
      'Adjust ball toss location to improve accuracy on missed targets.',
    ],
  },
  {
    id: 'pressure-serves',
    name: 'Pressure Serves',
    sourcePage: 'Training',
    sourceHref: '/training',
    defaultSets: 3,
    defaultReps: 1,
    workSeconds: 90,
    restSeconds: 30,
    instructions: [
      'Simulate pressure by assigning a consequence for double faults (e.g., 10 push-ups).',
      'Serve full games with self-imposed score pressure.',
      'Focus on pre-serve routine and consistent ball toss under stress.',
      'Use second-serve spin mechanics even on first serves to build confidence.',
    ],
  },
  {
    id: 'fatigue-serves',
    name: 'Fatigue Serves',
    sourcePage: 'Training',
    sourceHref: '/training',
    defaultSets: 5,
    defaultReps: 20,
    workSeconds: 90,
    restSeconds: 90,
    instructions: [
      'Run a short sprint or do jumping jacks before each set of serves.',
      'Serve 20 balls immediately after the physical effort.',
      'Track serve quality versus a non-fatigued baseline.',
      'Focus on maintaining technique when the body is tired.',
    ],
  },
  // Footwork page
  {
    id: 'baseline-shadow-rally',
    name: 'Baseline Shadow Rally',
    sourcePage: 'Footwork',
    sourceHref: '/footwork',
    defaultSets: 1,
    defaultReps: 1,
    workSeconds: 120,
    restSeconds: 30,
    instructions: [
      'Perform a full 2-minute shadow rally with no ball.',
      'Simulate forehand, backhand, and recover to center between each shot.',
      'Use split-step timing as if reading a live ball.',
      'Maintain consistent rhythm and recover fully to the center mark.',
    ],
  },
  {
    id: 'approach-volley-overhead',
    name: 'Approach-Volley-Overhead',
    sourcePage: 'Footwork',
    sourceHref: '/footwork',
    defaultSets: 3,
    defaultReps: 1,
    workSeconds: 90,
    restSeconds: 30,
    instructions: [
      'Coach feeds a short ball; player approaches and hits a groundstroke.',
      'Move forward and volley the next fed ball.',
      'Back up quickly for a lob and finish with an overhead.',
      'Focus on smooth transitions and proper positioning at each phase.',
    ],
  },
  // Mental Game page
  {
    id: 'first-to-7-tiebreak',
    name: 'First-to-7 Tiebreak',
    sourcePage: 'Mental Game',
    sourceHref: '/mental-game',
    defaultSets: 1,
    defaultReps: 1,
    workSeconds: 600,
    restSeconds: 0,
    instructions: [
      'Play a full tiebreak to 7 with standard tiebreak scoring rules.',
      'Apply a pre-point routine (bounce ball, deep breath, visualize) on every point.',
      'After each point, reset mentally by focusing on the next ball only.',
      'Debrief after the tiebreak: note which mental cues helped most under pressure.',
    ],
  },
];
